name: post_task
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.2

  # json parsing
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  
  # either - functional programming
  fpdart: ^0.6.0

  # network
  http: ^1.1.0
  
  # state management
  provider: ^6.0.5

  # network connection checker
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter
  flutter_lints: ^2.0.0

  # dart generator
  build_runner: ^2.4.6

  # json parsing
  json_serializable: ^6.7.1
  freezed: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
